language: swift
os: osx

git:
  depth: 1

stages:
  - name: test

branches:
  only:
  - master


jobs:
  include:
    - stage: test
      name: Run Unit Tests (iOS, Xcode 11.3)
      osx_image: xcode11.3
      script: Scripts/test.sh -d "OS=13.3,name=iPhone 11" -d "OS=12.4,name=iPhone X" -d "OS=11.4,name=iPhone SE"

    - stage: test
      name: Run Unit Tests (macOS, Xcode 11.3)
      osx_image: xcode11.3
      script: Scripts/test.sh -d "arch=x86_64"

    - stage: test
      name: Run Unit Tests (tvOS, Xcode 11.3)
      osx_image: xcode11.3
      script: Scripts/test.sh -d "OS=13.3,name=Apple TV 4K" -d "OS=11.4,name=Apple TV 4K"

    - stage: test
      name: Build (watchOS, Xcode 11.3)
      osx_image: xcode11.3
      script: Scripts/build.sh -d "OS=5.3,name=Apple Watch Series 3 - 42mm"

    - stage: test
      name: Run Unit Tests (iOS, Xcode 11.2)
      osx_image: xcode11.2
      script: Scripts/test.sh -d "OS=13.2.2,name=iPhone 11"

    - stage: test
      name: Run Unit Tests (iOS, Xcode 11)
      osx_image: xcode11
      script: Scripts/test.sh -d "OS=13.0,name=iPhone 11"

    - stage: test
      name: Swift Build (Swift Package Manager)
      osx_image: xcode11
      script: swift test

    # - os: linux
    #   language: generic
    #   dist: bionic
    #   sudo: required
    #   git:
    #     depth: 1
    #   stages:
    #     - name: test
    #       #branches:
    #       #only:
    #       #- master
    #   jobs:
    #     include:
    #       - stage: test
    #         name: Swift Build (Swift Package Manager)
    #         install:
    #           - sudo apt-get install clang libicu-dev
    #           - wget https://swift.org/builds/swift-5.2-release/ubuntu1804/swift-5.2-RELEASE/swift-5.2-RELEASE-ubuntu18.04.tar.gz
    #           - tar xzf swift-5.2-RELEASE-ubuntu18.04.tar.gz
    #           - export PATH="${PWD}/swift-5.2-RELEASE-ubuntu18.04/usr/bin:$PATH"
    #         script: swift test --enable-test-discovery
